In [1]:
'''write the code to convert the temperatur c to f'''
def celsius_to_fahrenheit(celsius):
    return (celsius * 9/5) + 32

# Example usage
celsius = 25
fahrenheit = celsius_to_fahrenheit(celsius)
print(f"{celsius}°C is equal to {fahrenheit}°F")


25°C is equal to 77.0°F


In [2]:
#individual carbo foot print
def calculate_carbon_footprint(transport_km, electricity_kwh, waste_kg):
    # Emission factors (in kg CO2 per unit)
    transport_emission_factor = 0.21  # kg CO2 per km (average car)
    electricity_emission_factor = 0.5  # kg CO2 per kWh (average electricity mix)
    waste_emission_factor = 0.25  # kg CO2 per kg of waste

    # Calculate emissions
    transport_emissions = transport_km * transport_emission_factor
    electricity_emissions = electricity_kwh * electricity_emission_factor
    waste_emissions = waste_kg * waste_emission_factor

    # Total carbon footprint
    total_emissions = transport_emissions + electricity_emissions + waste_emissions
    return total_emissions

# Example usage
transport_km = 100  # kilometers traveled by car
electricity_kwh = 200  # kilowatt-hours of electricity used
waste_kg = 50  # kilograms of waste produced

carbon_footprint = calculate_carbon_footprint(transport_km, electricity_kwh, waste_kg)
print(f"Your total carbon footprint is {carbon_footprint} kg CO2")


Your total carbon footprint is 133.5 kg CO2


In [3]:
# Using 'is' operator
a = [1, 2, 3]
b = a
c = [1, 2, 3]

print(a is b)  # True, because 'b' is the same object as 'a'
print(a is c)  # False, because 'c' is a different object, even though it has the same content

# Using 'in' operator
fruits = ['apple', 'banana', 'cherry']
print('banana' in fruits)  # True, because 'banana' is in the list 'fruits'
print('grape' in fruits)   # False, because 'grape' is not in the list 'fruits'


True
False
True
False


In [4]:
#How can we make any ptoduct sustainable 
#1. Eco-friendly
#2. Energy Efficient 
#3. Durability
#4. Ethical
#5. Minimum packaging

In [5]:
'''Creating an AI project involves several key stages, each crucial for the successful development and deployment of the AI system. Here's a typical AI project cycle:

### 1. Problem Definition
- **Identify the Problem**: Clearly define the problem you want to solve with AI.
- **Set Objectives**: Establish specific, measurable goals for the project.

### 2. Data Collection
- **Gather Data**: Collect relevant data from various sources.
- **Data Quality**: Ensure the data is accurate, complete, and representative.

### 3. Data Preparation
- **Data Cleaning**: Remove or correct any errors or inconsistencies in the data.
- **Data Transformation**: Convert data into a suitable format for analysis.
- **Feature Engineering**: Create new features or variables that can improve the model's performance.

### 4. Model Selection
- **Choose Algorithms**: Select appropriate machine learning algorithms based on the problem and data.
- **Baseline Model**: Develop a simple model to establish a performance baseline.

### 5. Model Training
- **Train Models**: Use the training data to build and train multiple models.
- **Hyperparameter Tuning**: Optimize the model's hyperparameters to improve performance.

### 6. Model Evaluation
- **Evaluate Models**: Assess the models using validation data and performance metrics.
- **Select Best Model**: Choose the model that performs best on the evaluation criteria.

### 7. Model Deployment
- **Deploy Model**: Integrate the model into the production environment.
- **Monitor Performance**: Continuously monitor the model's performance and make adjustments as needed.

### 8. Maintenance and Updates
- **Regular Updates**: Update the model with new data and retrain it periodically.
- **Performance Monitoring**: Keep track of the model's performance over time and address any issues that arise.
'''


"Creating an AI project involves several key stages, each crucial for the successful development and deployment of the AI system. Here's a typical AI project cycle:\n\n### 1. Problem Definition\n- **Identify the Problem**: Clearly define the problem you want to solve with AI.\n- **Set Objectives**: Establish specific, measurable goals for the project.\n\n### 2. Data Collection\n- **Gather Data**: Collect relevant data from various sources.\n- **Data Quality**: Ensure the data is accurate, complete, and representative.\n\n### 3. Data Preparation\n- **Data Cleaning**: Remove or correct any errors or inconsistencies in the data.\n- **Data Transformation**: Convert data into a suitable format for analysis.\n- **Feature Engineering**: Create new features or variables that can improve the model's performance.\n\n### 4. Model Selection\n- **Choose Algorithms**: Select appropriate machine learning algorithms based on the problem and data.\n- **Baseline Model**: Develop a simple model to establ

In [6]:
is_leap_year = lambda year: (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)

year = int(input("Enter the year Like 2002"))
print(f"{year} is a leap year: {is_leap_year(year)}")


Enter the year Like 2002 2024


2024 is a leap year: True


In [7]:
import pandas as pd

renewable_source = ["Solar", "Wind"]

data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

renewable_series = pd.Series(renewable_source)

print("Renewable:", renewable_series)


Renewable: 0    Solar
1     Wind
dtype: object


In [8]:
project_df = pd.DataFrame(data)
project_df.head()

Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

In [9]:

project_df = pd.DataFrame(data)

# Accessing the third row (index position 2)
specific_row = project_df.iloc[[1,2]]

specific_row.head()

Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
1             2024  
2             2022

In [10]:
project_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Project           5 non-null      object
 1   Technology        5 non-null      object
 2   Capacity (MW)     5 non-null      int64 
 3   Cost (Million $)  5 non-null      int64 
 4   Location          5 non-null      object
 5   Completion Year   5 non-null      int64 
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes


In [11]:
project_df.describe()

Capacity (MW)  Cost (Million $)  Completion Year
count        5.00000          5.000000         5.000000
mean       160.00000        260.000000      2023.400000
std         96.17692        119.373364         1.140175
min         50.00000        100.000000      2022.000000
25%        100.00000        200.000000      2023.000000
50%        150.00000        250.000000      2023.000000
75%        200.00000        350.000000      2024.000000
max        300.00000        400.000000      2025.000000

In [12]:
#filtration

project_df = pd.DataFrame(data)

# Filter projects with capacity more than 100 MW
high_capacity_projects = project_df[project_df["Capacity (MW)"] > 100]
high_capacity_projects.head()


Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022

In [13]:
#Add new column

project_df = pd.DataFrame(data)

# Add a new column for cost per MW
project_df["Cost per MW (Million $/MW)"] = project_df["Cost (Million $)"] / project_df["Capacity (MW)"]

project_df.head()


Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  Cost per MW (Million $/MW)  
0  California             2023                    1.333333  
1       Texas             2024                    1.333333  
2  Washington             2022                    1.750000  
3      Nevada             2025                    2.000000  
4       Idaho             2023                    2.500000

In [17]:
# sum finding

df = pd.DataFrame(data)

# Calculate total capacity for each type of technology
total_capacity = df.groupby("Technology")["Capacity (MW)"].sum()

print("Total Capacity for each type of technology:")
total_capacity.head()


Total Capacity for each type of technology:


Technology
Geothermal    100
Hydropower    200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64

In [ ]:
#Numpy

In [20]:
!pip install numpy

In [21]:
import numpy as np

one_d_array = np.array([1, 2, 3, 4, 5])

print("One-dimensional array:", one_d_array)


One-dimensional array: [1 2 3 4 5]


In [31]:
import numpy as np


two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Two-dimensional array:")
print(two_d_array)


Two-dimensional array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
import numpy as np

# Create a three-dimensional array
three_d_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("Three-dimensional array:")
print(three_d_array)


Three-dimensional array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [24]:
three_d_array.shape

(2, 2, 3)

In [26]:
three_d_array.ndim

3

In [27]:
three_d_array.size

12

In [28]:
three_d_array.dtype

dtype('int64')

In [33]:
three_d_array.itemsize

8

In [32]:
two_d_array.itemsize

8

In [35]:
np.ones(3)

array([1., 1., 1.])

In [38]:
np.zeros(3)


array([0., 0., 0.])

In [37]:
np.random.random(5)

array([0.1141933 , 0.08141418, 0.6704471 , 0.41858023, 0.42975133])

In [41]:
array = np.full((16,16),5)
print(array)

[[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]]


In [45]:
identity = np.identity(6)
print(identity)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [49]:
arrange = np.arange(7)
print(arrange)
arrange = np.arange(1,20,3)
print(arrange)

[0 1 2 3 4 5 6]
[ 1  4  7 10 13 16 19]


In [50]:
arrange = np.linspace(1,20,3)
print(arrange)

[ 1.  10.5 20. ]


In [51]:
import numpy as np

# With endpoint=True (default)
array_with_endpoint = np.linspace(1, 20, 3, endpoint=True)
print("With endpoint=True:", array_with_endpoint)

# With endpoint=False
array_without_endpoint = np.linspace(1, 20, 3, endpoint=False)
print("With endpoint=False:", array_without_endpoint)


With endpoint=True: [ 1.  10.5 20. ]
With endpoint=False: [ 1.          7.33333333 13.66666667]


In [52]:
#indexing

In [53]:
import numpy as np

# Create a one-dimensional array
one_d_array = np.array([10, 20, 30, 40, 50])

# Access the first element
first_element = one_d_array[0]
print("First element:", first_element)

# Access the last element
last_element = one_d_array[-1]
print("Last element:", last_element)


First element: 10
Last element: 50


In [54]:
import numpy as np

# Create a one-dimensional array
one_d_array = np.array([10, 20, 30, 40, 50])

# Find the middle index
middle_index = len(one_d_array) // 2

# Print the middle number
middle_number = one_d_array[middle_index]
print("Middle number:", middle_number)


Middle number: 30


In [55]:
#palidrome

one_d_array = np.array([10, 20, 30, 40, 50])
print(one_d_array [::-1])

[50 40 30 20 10]


In [61]:
def is_palindrome(number):
    # Convert the number to a string
    num_str = str(number)
    # Check if the string is equal to its reverse
    return num_str == num_str[::-1]

# Test the function
number = one_d_array
if is_palindrome(number):
    print(f"{number} is a palindrome number.")
else:
    print(f"{number} is not a palindrome number.")


[10 20 30 40 50] is not a palindrome number.


In [71]:
data = np.array([2, 3, 4, 5, 6, 7, 8,6,7])
reshaped_data = data.reshape(3, 3)
print("Reshaped array:")
print(reshaped_data.T)


Reshaped array:
[[2 5 8]
 [3 6 6]
 [4 7 7]]


In [72]:
data = np.array([2, 3, 4, 5, 6, 7, 8,6,7])
reshaped_data = data.reshape(3, 3)
print("Reshaped array:")
print(reshaped_data)


Reshaped array:
[[2 3 4]
 [5 6 7]
 [8 6 7]]


In [77]:
#for column wise

data = np.array([2, 3, 4, 5, 6, 7, 8,6,7])
reshaped_data = data.reshape(3, 3)
print("Reshaped array:")
print(reshaped_data.flatten('F'))


Reshaped array:
[2 5 8 3 6 6 4 7 7]


In [76]:
#for row value
data = np.array([2, 3, 4, 5, 6, 7, 8,6,7])
reshaped_data = data.reshape(3, 3)
print("Reshaped array:")
print(reshaped_data.flatten())


Reshaped array:
[2 3 4 5 6 7 8 6 7]


In [ ]:
#write statical word for example in pyhton

In [78]:

data = np.array([2, 3, 4, 5, 6, 7])

mean = np.mean(data)
print("Mean:", mean)

median = np.median(data)
print("Median:", median)

std_dev = np.std(data)
print("Standard Deviation:", std_dev)

variance = np.var(data)
print("Variance:", variance)

total_sum = np.sum(data)
print("Sum:", total_sum)


Mean: 5.0
Median: 5.0
Standard Deviation: 2.0
Variance: 4.0
Sum: 35


In [81]:

data = np.array([2, 3, 4, 5, 6, 7])


reshaped_data = data.reshape(2, 3)

print("Reshaped array:")
print(reshaped_data)


Reshaped array:
[[2 3 4]
 [5 6 7]]


In [ ]:
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}



